version: '3.1'
services:
  stats-server:
    build: ./ExploreWithMeStatistics
    container_name: stats-server-iff
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme-stats
      - SPRING_DATASOURCE_USERNAME=explorerstat
      - SPRING_DATASOURCE_PASSWORD=explorerstat

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explorewithme-stats
      - POSTGRES_USER=explorerstat
      - POSTGRES_PASSWORD=explorerstat

  ewm-service:
    build: ./ExploreWithMeServer
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - TZ="Europe/Moscow"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=explorer
      - SPRING_DATASOURCE_PASSWORD=explorer
      - STATISTIC_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=explorer
      - POSTGRES_PASSWORD=explorer
