version: '3.8'
services:
  stats-server:
    build: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - POSTGRES_USER=dima
      - POSTGRES_PASSWORD=password
  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=dima
      - POSTGRES_PASSWORD=password
  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - POSTGRES_USER=dima
      - POSTGRES_PASSWORD=password
  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=dima
      - POSTGRES_PASSWORD=password




